version: "3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    hostname: sql_server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes: 
      - mssql-volume:/var/opt/mssql
volumes: 
  mssql-volume: